### ISSUE TITLE
swift 3.0 support

### ISSUE THREAD

**Issue by mrtj** [ReactiveKit/ReactiveFoundation#6]
This framework does not compile with swift 3.0 compiler. If I set the compiler to legacy swift 2.x versions, as ReactiveFoundation depends also on ReactiveKit, this later also should be compiled with swift 2.x settings so it can not be used in newer projects.

**Comment by srdanrasic** [comment]
This framework is deprecated. ReactiveKit supports Swift 3 since version 3. Features from ReactiveFoundation and ReactiveUIKit have been merged into Bond framework.

https://github.com/ReactiveKit/ReactiveKit#migration-from-v2x-to-v3x
